services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: akibaz
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/data/postgres
    networks:
      - postgres_net
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_db:/var/lib/pgadmin
    networks:
      - postgres_net
    restart: unless-stopped
    depends_on:
      - db

volumes:
  postgres_db:
  pgadmin_db:
networks:
  postgres_net:
    driver: bridge